apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudstate-vn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudstate-vn
  template:
    metadata:
      labels:
        app: cloudstate-vn
    spec:
      containers:
      - name: cloudstate-vn
        image: nginx
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule